name: Publish Docker Image

on:
  push:
    branches:  [ main1 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME_AccountDataIngestionService: rakeshbp97/accountdataingestionservice 
  IMAGE_NAME_AccountProcessService: rakeshbp97/accountprocessservice
  # IMAGE_NAME: ${{ github.repository }} # returns Waterlabsadmin/github-actions-course : problem with uppercase
#   IMAGE_TAG: 1.0.${{ github.run_number +26 }} # GITHUB_RUN_NUMBER }}
  NUM: ${{ github.run_number }}
  run: |
          echo "IMAGE_TAG= 1.0.$(($NUM+18))" >> $GITHUB_ENV
          - run: echo $IMAGE_TAG

jobs:
  build-push-docker:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
#        - name: run number with offset
#          NUM: ${{ github.run_number }}
#          run: |
#           echo ::set-env name=IMAGE_TAG::$(($NUM+200))
#           - run: echo $IMAGE_TAG

      - name: Checkout repository
        uses: actions/checkout@v3


      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TRANSFORMRCMIMAGE }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract AccountDataIngestionService Docker metadata
        id: accountdataingestionservice-meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_AccountDataIngestionService }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push AccountDataIngestionService Docker image
        id: accountdataingestionservice-build-and-push
        uses: docker/build-push-action@v3
        with:
          context: AccountDataIngestionService
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_AccountDataIngestionService }}:${{ env.IMAGE_TAG }} # ${{ steps.meta.outputs.tags }}
          # tags: ghcr.io/houssemdellai/github-actions-course:${{ env.IMAGE_TAG }} # ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.accountdataingestionservice-meta.outputs.labels }}
          
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract AccountProcessService Docker metadata
        id: accountprocessservice-meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_AccountProcessService }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push AccountProcessService Docker image
        id: accountprocessservice-build-and-push
        uses: docker/build-push-action@v3
        with:
          context: AccountProcessService
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_AccountProcessService }}:${{ env.IMAGE_TAG }} # ${{ steps.meta.outputs.tags }}
          # tags: ghcr.io/houssemdellai/github-actions-course:${{ env.IMAGE_TAG }} # ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.accountprocessservice-meta.outputs.labels }}
          
#       # Delete old version of Docker image
# #       - name: Delete old version of Docker image
# #         id: delete-old-version
#       - uses: bots-house/ghcr-delete-image-action@v1.0.0
#         with:
#           owner: rakeshbp97
#           name: accountdataingestionservice
#           token: ${{ secrets.TRANSFORMRCMIMAGE }}
#           tag: 1.0.1
